import type { Metadata } from "next";
import "./globals.css";
import "easymde/dist/easymde.min.css";
import { Toaster } from "@/components/ui/toaster";
import { DarkModeProvider } from "./context/DarkModeContext";

export const metadata: Metadata = {
  title: "Blog-Next-Sanity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased bg-[rgb(250,250,250)] dark:bg-black`}>
        <DarkModeProvider>
          {children}
          <Toaster />
        </DarkModeProvider>
      </body>
    </html>
  );
}
